server:
  port: 8080
eureka:
  instance:
    hostname: accounts
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: fulfillment
  data:
    mongodb:
      uri: mongodb://mongo:27017/fulfillment
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      accounts-customer: accounts.customer.change
      orders-order: orders.order.fulfill
      fulfillment-order: fulfillment.order.change
    consumer:
      group-id: fulfillment
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
---
server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  config:
    activate:
      on-profile: gke